"""
Django settings for user project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta # jwt token life time...
import pymysql  # 추가
pymysql.install_as_MySQLdb() # 추가


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-l+ej9xz)72wtdd8sy#1g_l--y+#8$&c)l6=^@b3b3v+2ozhhwb'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
#DEBUG = False

ALLOWED_HOSTS = ['*']

# CSRF TOOKEN (Session)
# CSRF_COOKIE_SECURE = True

# Nginx가 X-Forwarded-Proto 헤더를 'https'로 설정하여 전달할 경우,
# Django는 이 요청을 secure한 요청으로 인식합니다.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'account',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware'
]

ROOT_URLCONF = 'user.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'user.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME' : 'appBackend',
        'USER' : 'appback',
        'PASSWORD' : 'appback12@#',
        'PORT' : '3306',
        'HOST' : '10.10.20.10'
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ko-KR'
TIME_ZONE = 'Asia/Seoul'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = '/var/www/app/user/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST JWT
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}
# JWT SETTINGS
SIMPLE_JWT = {
    # 액세스 토큰의 유효 기간을 설정 5
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    # 리프레시 토큰의 유효 기간 timedelta(days=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=90),
    # 리프레시 토큰을 사용할 때마다 새로운 리프레시 토큰을 발급할지 여부
    # True로 설정하면 리프레시 토큰이 매번 갱신되어, 토큰 탈취 시 공격자가 사용할 수 있는 기회를 줄여 보안을 강화
    'ROTATE_REFRESH_TOKENS': True,
    # True일 때, 이전의 리프레시 토큰을 블랙리스트에 추가할지 여부를 설정합니다.
    'BLACKLIST_AFTER_ROTATION': False
}

# 사용자 인증
AUTH_USER_MODEL = 'account.UserInfo'

# SMTP
# 이메일 백엔드 설정 (SMTP 사용)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#EMAIL_BACKEND = 'account.email_backend.CustomEmailBackend'
# 메일 호스트 (SMTP 서버 주소)
# 예: Gmail의 경우 'smtp.gmail.com'
EMAIL_HOST = 'smtp.gmail.com'
# 메일 서버 포트
# 보안 연결에 따라 587 (TLS) 또는 465 (SSL)
EMAIL_PORT = 587
# 💡 SSL 사용: True로 설정
EMAIL_USE_SSL = False
# 💡 TLS는 사용하지 않음: SSL과 TLS를 동시에 True로 설정하면 안 됩니다.
EMAIL_USE_TLS = True
# 메일 서버 인증에 사용할 사용자 이름 (보내는 이메일 주소)
EMAIL_HOST_USER = 'rnd.ventigen@gmail.com'
# 메일 서버 인증에 사용할 비밀번호 (실제 이메일 비밀번호가 아닌 '앱 비밀번호'를 사용해야 할 수 있음)
# 메일 전용 비밀번호 사용
EMAIL_HOST_PASSWORD = 'qjrq ezwg fxei iolb'
#EMAIL_HOST_PASSWORD = 'oas12w3e4r'
# 기본 발신자 이메일 주소
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
