# Generated by Django 5.2.7 on 2025-11-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OasGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oas_group_id', models.CharField(max_length=50, verbose_name='환경제어기 그룹 ID')),
                ('oas_info_id', models.CharField(max_length=50, verbose_name='환경제어기 정보 ID')),
                ('oas_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='사용자 정의 환경제어기 이름')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 날짜')),
            ],
            options={
                'verbose_name': '환경제어기 그룹 정보',
                'verbose_name_plural': '환경제어기 그룹 정보',
                'db_table': 'oas_group',
            },
        ),
        migrations.CreateModel(
            name='OasInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=10, verbose_name='지역 코드')),
                ('dong', models.CharField(max_length=4, verbose_name='아파트 동')),
                ('ho', models.CharField(max_length=4, verbose_name='아파트 호')),
                ('oas_id', models.CharField(max_length=2, verbose_name='환경 제어기 ID')),
                ('device_id', models.CharField(max_length=20, unique=True, verbose_name='환경 제어기 Device ID')),
                ('room', models.BinaryField(blank=True, max_length=100, null=True, verbose_name='원격 관리에서 정해진 방 이름')),
                ('auth', models.BooleanField(default=False, verbose_name='환경 제어기 인증 상태')),
                ('auth_count', models.SmallIntegerField(default=0, verbose_name='환경 제어기 인증 횟수')),
                ('auth_date', models.DateField(blank=True, null=True, verbose_name='환경 제어기 인증 날짜')),
                ('lock', models.BooleanField(default=False, verbose_name='잠금 상태')),
                ('lock_date', models.DateField(blank=True, null=True, verbose_name='잠김 날짜')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 날짜')),
            ],
            options={
                'verbose_name': '환경 제어기 정보',
                'verbose_name_plural': '환경 제어기 정보',
                'db_table': 'oas_info',
                'unique_together': {('oas_id', 'device_id')},
            },
        ),
    ]
