# Generated by Django 5.2.7 on 2025-11-24 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oasinfo',
            old_name='device_id',
            new_name='deviceId',
        ),
        migrations.AlterUniqueTogether(
            name='oasinfo',
            unique_together={('site', 'deviceId')},
        ),
    ]
