# Generated by Django 5.2.7 on 2025-11-24 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_rename_device_id_oasinfo_deviceid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oasinfo',
            options={'verbose_name': '환경제어기 정보', 'verbose_name_plural': '환경제어기 정보'},
        ),
    ]
