# Generated by Django 5.2.7 on 2025-11-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_alter_oasinfo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oasinfo',
            name='room',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='원격 관리에서 정해진 방 이름'),
        ),
    ]
