# Generated by Django 5.2.7 on 2025-11-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_alter_oasinfo_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oasinfo',
            name='deviceId',
            field=models.CharField(max_length=50, unique=True, verbose_name='환경 제어기 Device ID'),
        ),
        migrations.AlterField(
            model_name='oasinfo',
            name='room',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='방 이름'),
        ),
    ]
