# Generated by Django 5.2.7 on 2025-11-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_alter_oasinfo_deviceid_alter_oasinfo_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oasinfo',
            name='deviceId',
            field=models.CharField(max_length=50, verbose_name='환경 제어기 Device ID'),
        ),
    ]
