# Generated by Django 5.2.7 on 2025-11-27 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0006_alter_oasinfo_deviceid'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='oasinfo',
            unique_together=set(),
        ),
    ]
