# Generated by Django 5.2.7 on 2025-12-04 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0007_alter_oasinfo_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oasgroup',
            name='oas_info_id',
        ),
        migrations.AddField(
            model_name='oasgroup',
            name='oas_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='device.oasinfo', verbose_name='환경제어기 정보'),
            preserve_default=False,
        ),
    ]
