# Generated by Django 5.2.7 on 2025-12-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0008_remove_oasgroup_oas_info_id_oasgroup_oas_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oasgroup',
            name='oas_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='환경제어기 이름'),
        ),
    ]
