# Generated by Django 5.2.6 on 2025-10-23 04:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='이메일')),
                ('family_level', models.CharField(choices=[('master', 'master'), ('user', 'user'), ('none', 'none')], default='none', max_length=20, verbose_name='가족 레벨')),
                ('nick_name', models.CharField(max_length=50, unique=True, verbose_name='닉네임')),
                ('oas_group_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='환경제어 그룹 ID')),
                ('family_auth_count', models.SmallIntegerField(default=0, unique=True, verbose_name='인증 중인 가족 수')),
                ('family_group_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='가족 그룹 ID')),
                ('user_email_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='사용자 이메일 ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='계정 활성 상태')),
                ('is_staff', models.BooleanField(default=False, verbose_name='관리자 사이트 접근')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='최고 권한자')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성 날짜')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '사용자 정보',
                'verbose_name_plural': '사용자 정보',
                'db_table': 'user_info',
            },
        ),
        migrations.CreateModel(
            name='UserEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_auth', models.BooleanField(default=False, verbose_name='이메일 인증 상태')),
                ('email_auth_count', models.SmallIntegerField(default=0, verbose_name='이메일 인증 횟수')),
                ('email_auth_date', models.DateField(blank=True, null=True, verbose_name='이메일 인증 날짜')),
                ('email_auth_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='이메일 인증 코드')),
                ('email_refresh_count', models.SmallIntegerField(default=0, verbose_name='이메일 다시 전송 횟수')),
                ('email_auth_lock', models.BooleanField(default=False, verbose_name='이메일 인증 잠김')),
                ('email_lock_time', models.DateTimeField(blank=True, null=True, verbose_name='이메일 잠김 시간')),
                ('email_reauth_count', models.SmallIntegerField(default=0, verbose_name='이메일 재 인증 횟수')),
                ('email_reauth_lock', models.BooleanField(default=False, verbose_name='이메일 재 인증 잠김')),
                ('email_reauth_date', models.DateField(blank=True, null=True, verbose_name='이메일 재 인증 잠김 날짜')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_info', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 이메일',
                'verbose_name_plural': '사용자 이메일',
                'db_table': 'user_email',
            },
        ),
    ]
