# Generated by Django 5.2.6 on 2025-10-23 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='family_auth_count',
            field=models.SmallIntegerField(default=0, verbose_name='인증 중인 가족 수'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='family_group_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='가족 그룹 ID'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='nick_name',
            field=models.CharField(max_length=50, verbose_name='닉네임'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='oas_group_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='환경제어 그룹 ID'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_email_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='사용자 이메일 ID'),
        ),
    ]
