# Generated by Django 5.2.6 on 2025-10-23 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_userinfo_family_auth_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='user_email_id',
        ),
    ]
