# Generated by Django 5.2.6 on 2025-10-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_userinfo_user_email_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OasGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oas_group_id', models.CharField(max_length=50, verbose_name='환경 제어 그룹 ID')),
                ('oas_info_id', models.CharField(max_length=50, verbose_name='환경 제어기 정보 ID')),
                ('oas_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='사용자 정의 제어기 이름')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 날짜')),
            ],
            options={
                'verbose_name': '환경 제어기 등록 정보',
                'verbose_name_plural': '환경 제어기 등록 정보',
                'db_table': 'oas_group',
            },
        ),
    ]
