# Generated by Django 5.2.7 on 2025-10-31 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_oasinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='useremail',
            name='email_code_date',
            field=models.DateField(blank=True, null=True, verbose_name='코드 생성 날짜'),
        ),
    ]
