# Generated by Django 5.2.7 on 2025-11-04 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_useremail_email_code_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='대상 이메일')),
                ('task_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Celery 작업 ID')),
                ('log_type', models.CharField(default='FAILURE', max_length=50, verbose_name='로그 타입 (SUCCESS/FAILURE 등)')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='오류 메시지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='기록 시간')),
            ],
            options={
                'verbose_name': '이메일 로그',
                'verbose_name_plural': '이메일 로그',
                'ordering': ['-created_at'],
            },
        ),
    ]
