# Generated by Django 5.2.7 on 2025-11-04 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_emaillog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremail',
            name='email_code_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='코드 생성 날짜'),
        ),
    ]
