# Generated by Django 5.2.7 on 2025-11-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_useremail_email_code_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='new_email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='새 이메일 (변경 대기 중)'),
        ),
    ]
