# Generated by Django 5.2.7 on 2025-11-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_userinfo_new_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremail',
            name='email_reauth_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='이메일 재 인증 잠김 날짜'),
        ),
    ]
