# Generated by Django 5.2.7 on 2025-11-24 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_useremail_email_reauth_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OasGroup',
        ),
        migrations.DeleteModel(
            name='OasInfo',
        ),
    ]
