# Generated by Django 5.2.7 on 2025-12-01 13:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_delete_oasgroup_delete_oasinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_group_id', models.CharField(help_text='가족 그룹을 식별하는 고유 ID (예: fam_1)', max_length=50, verbose_name='가족 그룹 ID')),
                ('master_id', models.CharField(help_text='그룹 내 마스터 권한을 가진 사용자 ID(User 모델 참조)', max_length=50, verbose_name='Family Level 마스터')),
                ('user_id', models.BigIntegerField(help_text='그룹에 소속된 사용자 (User 모델 참조)', verbose_name='사용자 ID')),
                ('email', models.CharField(help_text='사용자 기준 이메일', max_length=254, verbose_name='이메일')),
                ('nick_name', models.CharField(help_text='사용자 기준 닉네임', max_length=50, verbose_name='닉네임')),
                ('family_level', models.CharField(choices=[('master', '마스터'), ('user', '일반 사용자')], default='user', help_text='그룹 내 권한 레벨 (master 또는 user)', max_length=10, verbose_name='가족 레벨')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성 일자')),
            ],
            options={
                'verbose_name': '가족 그룹',
                'verbose_name_plural': '가족 그룹',
                'db_table': 'user_group',
            },
        ),
    ]
