# Generated by Django 5.2.7 on 2025-12-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_usergroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='new_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='새 이메일 (변경 대기 중)'),
        ),
    ]
