# Generated by Django 5.2.7 on 2025-12-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_userinfo_email_alter_userinfo_new_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='decryption_fail_count',
            field=models.IntegerField(default=0, verbose_name='복호화 연속 실패 횟수'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='last_fail_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='마지막 복호화 실패 시간'),
        ),
    ]
