# Generated by Django 5.2.7 on 2025-12-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_userinfo_decryption_fail_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='user_id',
            field=models.BigIntegerField(help_text='그룹에 소속된 사용자 (User 모델 참조)', unique=True, verbose_name='사용자 ID'),
        ),
    ]
