# Generated by Django 5.2.7 on 2025-12-03 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_usergroup_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='id',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='user_id',
        ),
        migrations.AddField(
            model_name='usergroup',
            name='user',
            field=models.OneToOneField(default=1, help_text='그룹에 소속된 사용자 (UserInfo 모델과 1:1 연결)', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='사용자 ID'),
            preserve_default=False,
        ),
    ]
