# Generated by Django 5.2.7 on 2025-12-03 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_remove_usergroup_id_remove_usergroup_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='family_level',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='master_id',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='nick_name',
        ),
    ]
