# Generated by Django 5.2.7 on 2025-12-09 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('email_change', '이메일 변경 요청'), ('group_join', '그룹 가입 요청'), ('data_access', '특정 데이터 접근 요청')], max_length=50, verbose_name='요청 유형')),
                ('details', models.JSONField(blank=True, default=dict, null=True, verbose_name='요청 상세 정보 (JSON)')),
                ('status', models.CharField(choices=[('pending', '대기 중'), ('approved', '승인됨'), ('rejected', '거부됨'), ('canceled', '취소됨')], default='pending', max_length=20, verbose_name='상태')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='요청 시각')),
                ('approved_or_rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='처리 시각')),
                ('reason', models.TextField(blank=True, verbose_name='처리 사유')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL, verbose_name='승인자 (마스터 권한)')),
                ('requestee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL, verbose_name='요청자 (일반 사용자)')),
            ],
            options={
                'verbose_name': '승인 요청',
                'verbose_name_plural': '승인 요청',
                'ordering': ['-requested_at'],
            },
        ),
    ]
