# Generated by Django 5.2.7 on 2025-12-10 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelCooldown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('email_change', '이메일 변경 요청'), ('group_join', '그룹 가입 요청'), ('data_access', '특정 데이터 접근 요청')], max_length=50, verbose_name='요청 유형')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, verbose_name='마지막 삭제 시각')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooldown_records', to=settings.AUTH_USER_MODEL, verbose_name='쿨다운 사용자')),
            ],
            options={
                'verbose_name': '취소 쿨다운 기록',
                'ordering': ['-deleted_at'],
                'unique_together': {('user', 'request_type')},
            },
        ),
    ]
