# Generated by Django 5.2.7 on 2025-11-24 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=50, verbose_name='발생 앱')),
                ('logged_at', models.DateTimeField(auto_now_add=True, verbose_name='기록 시간')),
                ('level', models.CharField(max_length=10, verbose_name='심각도')),
                ('event_type', models.CharField(max_length=100, verbose_name='이벤트 타입')),
                ('message', models.TextField(verbose_name='상세 메시지')),
                ('request_data', models.TextField(blank=True, null=True, verbose_name='요청 데이터')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='관련 사용자')),
            ],
            options={
                'verbose_name': '통합 이벤트 기록',
                'verbose_name_plural': '통합 이벤트 기록',
                'db_table': 'project_log_entry',
                'ordering': ['-logged_at'],
            },
        ),
    ]
